"""
Demo: Sunrise Family Clinic — 5 AI Vendors
Demonstrates the full range of risk levels and finding types.
Run: python run_audit.py
"""

from auditor.schema import (
    VendorIntake, BAAStatus, DataResidency, VendorCategory, ModelTraining
)


PRACTICE_NAME = "Sunrise Family Clinic"
PRACTICE_SIZE = "Small (8 providers, 2 locations)"
AUDITOR_NAME = "Noah Mills, Healthcare Cybersecurity Consultant"


VENDORS = [

    # ── 1. Nuance DAX Copilot (Epic ambient scribe — generally well-governed)
    VendorIntake(
        vendor_name="Nuance / Microsoft",
        product_name="DAX Copilot",
        vendor_category=VendorCategory.AMBIENT_SCRIBE,
        version_or_date="2024 Q4",
        phi_touches_product=True,
        phi_types_accessed=["clinical notes", "demographics", "visit reason"],
        baa_status=BAAStatus.SIGNED,
        baa_date_signed="2024-03-15",
        data_residency=DataResidency.US_ONLY,
        data_leaves_us=False,
        data_encrypted_at_rest=True,
        data_encrypted_in_transit=True,
        data_retention_days=365,
        data_deletion_policy="PHI deleted within 30 days of contract termination",
        subprocessors_documented=True,
        model_training=ModelTraining.NOT_TRAINED_ON_PHI,
        model_trained_on_clinic_data=False,
        model_type_disclosed=True,
        human_oversight_required=True,
        sso_mfa_supported=True,
        rbac_supported=True,
        audit_logging_available=True,
        ai_governance_policy_exists=True,
        accountability_owner_named=True,
        incident_response_plan_covers_ai=True,
        use_case_documented=True,
        clinical_impact_documented=True,
        is_fda_regulated_device=False,
        third_party_audit_completed=True,
        bias_testing_performed=True,
        performance_metrics_disclosed=True,
        model_drift_monitoring=True,
        rollback_plan_exists=True,
        vendor_breach_notification_sla_hours=48,
        last_pentest_date="2024-09-01",
        soc2_or_hitrust_certified=True,
        currently_deployed=True,
        date_deployed="2024-04-01",
        staff_trained_on_tool=True,
        tool_in_ai_inventory=True,
        auditor_notes="Well-governed. BAA in place, SOC2 + HITRUST certified. Annual review recommended.",
    ),

    # ── 2. Generic AI Scheduling Bot (medium risk — BAA pending, unknown model)
    VendorIntake(
        vendor_name="ClearPath AI",
        product_name="SmartSchedule Pro",
        vendor_category=VendorCategory.SCHEDULING,
        version_or_date="v2.1",
        phi_touches_product=True,
        phi_types_accessed=["demographics", "appointment history", "insurance"],
        baa_status=BAAStatus.PENDING,
        data_residency=DataResidency.US_AND_INTERNATIONAL,
        data_leaves_us=True,
        data_encrypted_at_rest=True,
        data_encrypted_in_transit=True,
        data_retention_days=730,
        data_deletion_policy="",
        subprocessors_documented=False,
        model_training=ModelTraining.TRAINED_UNKNOWN,
        model_trained_on_clinic_data=None,
        model_type_disclosed=False,
        human_oversight_required=True,
        sso_mfa_supported=True,
        rbac_supported=True,
        audit_logging_available=True,
        ai_governance_policy_exists=False,
        accountability_owner_named=False,
        incident_response_plan_covers_ai=False,
        use_case_documented=True,
        clinical_impact_documented=False,
        is_fda_regulated_device=False,
        third_party_audit_completed=False,
        bias_testing_performed=False,
        performance_metrics_disclosed=False,
        model_drift_monitoring=False,
        rollback_plan_exists=False,
        vendor_breach_notification_sla_hours=None,
        last_pentest_date=None,
        soc2_or_hitrust_certified=False,
        currently_deployed=True,
        date_deployed="2024-08-01",
        staff_trained_on_tool=True,
        tool_in_ai_inventory=False,
        auditor_notes="BAA must be executed before continued use. Data leaves US — verify international transfer agreements.",
    ),

    # ── 3. ChatGPT (staff are pasting notes — CRITICAL, no BAA)
    VendorIntake(
        vendor_name="OpenAI",
        product_name="ChatGPT (Consumer)",
        vendor_category=VendorCategory.GENERAL_LLM,
        version_or_date="GPT-4o (web app)",
        phi_touches_product=True,   # staff pasting notes
        phi_types_accessed=["clinical notes", "demographics", "diagnoses"],
        baa_status=BAAStatus.NOT_SIGNED,
        data_residency=DataResidency.UNKNOWN,
        data_leaves_us=None,
        data_encrypted_at_rest=None,
        data_encrypted_in_transit=True,
        data_retention_days=30,
        data_deletion_policy="OpenAI may retain inputs for model training unless opt-out enabled",
        subprocessors_documented=False,
        model_training=ModelTraining.FINE_TUNED_ON_PHI,
        model_trained_on_clinic_data=True,   # patient data being sent in prompts
        model_type_disclosed=True,
        human_oversight_required=False,
        sso_mfa_supported=False,
        rbac_supported=False,
        audit_logging_available=False,
        ai_governance_policy_exists=None,
        accountability_owner_named=False,
        incident_response_plan_covers_ai=False,
        use_case_documented=False,
        clinical_impact_documented=False,
        is_fda_regulated_device=False,
        third_party_audit_completed=False,
        bias_testing_performed=None,
        performance_metrics_disclosed=False,
        model_drift_monitoring=False,
        rollback_plan_exists=False,
        vendor_breach_notification_sla_hours=None,
        last_pentest_date=None,
        soc2_or_hitrust_certified=False,
        currently_deployed=True,    # employees using it
        date_deployed="2023-12-01",
        staff_trained_on_tool=False,
        tool_in_ai_inventory=False,
        auditor_notes="SHADOW AI: Staff are pasting patient notes into consumer ChatGPT. No BAA. OpenAI's consumer product explicitly prohibits healthcare PHI. Immediate remediation required.",
    ),

    # ── 4. Billing automation — moderate risk, BAA signed but gaps
    VendorIntake(
        vendor_name="Waystar",
        product_name="AI Claims Assistant",
        vendor_category=VendorCategory.BILLING,
        version_or_date="2025 v1",
        phi_touches_product=True,
        phi_types_accessed=["billing codes", "insurance info", "demographics"],
        baa_status=BAAStatus.SIGNED,
        baa_date_signed="2025-01-10",
        data_residency=DataResidency.US_ONLY,
        data_leaves_us=False,
        data_encrypted_at_rest=True,
        data_encrypted_in_transit=True,
        data_retention_days=2190,   # 6 years — standard for billing
        data_deletion_policy="Retained 6 years per CMS requirements",
        subprocessors_documented=True,
        model_training=ModelTraining.NOT_TRAINED_ON_PHI,
        model_trained_on_clinic_data=False,
        model_type_disclosed=False,
        human_oversight_required=True,
        sso_mfa_supported=True,
        rbac_supported=True,
        audit_logging_available=True,
        ai_governance_policy_exists=True,
        accountability_owner_named=True,
        incident_response_plan_covers_ai=False,
        use_case_documented=True,
        clinical_impact_documented=False,
        is_fda_regulated_device=False,
        third_party_audit_completed=True,
        bias_testing_performed=False,
        performance_metrics_disclosed=False,
        model_drift_monitoring=True,
        rollback_plan_exists=True,
        vendor_breach_notification_sla_hours=72,
        last_pentest_date="2024-11-01",
        soc2_or_hitrust_certified=True,
        currently_deployed=True,
        date_deployed="2025-02-01",
        staff_trained_on_tool=True,
        tool_in_ai_inventory=True,
        auditor_notes="Solid baseline. IR plan should be updated to cover AI-specific failure modes. Bias testing not applicable for billing AI but document rationale.",
    ),

    # ── 5. Epic in-EHR AI (high trust but governance gaps at clinic level)
    VendorIntake(
        vendor_name="Epic Systems",
        product_name="Epic AI (Sepsis Predictor + In-Basket AI)",
        vendor_category=VendorCategory.EHR_INTEGRATED,
        version_or_date="2025 Feb Update",
        phi_touches_product=True,
        phi_types_accessed=["full EHR", "labs", "vitals", "diagnoses", "medications"],
        baa_status=BAAStatus.SIGNED,
        baa_date_signed="2021-07-01",
        data_residency=DataResidency.US_ONLY,
        data_leaves_us=False,
        data_encrypted_at_rest=True,
        data_encrypted_in_transit=True,
        data_retention_days=3650,
        data_deletion_policy="Per Epic contract and state medical records retention law",
        subprocessors_documented=True,
        model_training=ModelTraining.TRAINED_WITH_CONSENT,
        model_trained_on_clinic_data=True,
        model_type_disclosed=True,
        human_oversight_required=True,
        sso_mfa_supported=True,
        rbac_supported=True,
        audit_logging_available=True,
        ai_governance_policy_exists=True,
        accountability_owner_named=None,    # Clinic hasn't designated a local AI owner
        incident_response_plan_covers_ai=False,
        use_case_documented=True,
        clinical_impact_documented=True,
        is_fda_regulated_device=False,      # Sepsis predictor classified as CDS, not SaMD
        third_party_audit_completed=True,
        bias_testing_performed=True,
        performance_metrics_disclosed=True,
        model_drift_monitoring=True,
        rollback_plan_exists=True,
        vendor_breach_notification_sla_hours=24,
        last_pentest_date="2024-12-01",
        soc2_or_hitrust_certified=True,
        currently_deployed=True,
        date_deployed="2021-09-01",
        staff_trained_on_tool=False,        # AI features added without staff re-training
        tool_in_ai_inventory=False,         # Clinic doesn't track which Epic AI modules are active
        auditor_notes="Epic is well-governed at vendor level. Clinic-level gaps: no designated AI accountability owner, new AI features (In-Basket AI, Sep predictor) not in AI inventory, staff not re-trained when AI features were enabled by Epic.",
    ),
]
